version: '3.7'

services:
  sq:
    container_name: sq${BUILD}
    image: sonarqube:${SQ_VERSION}
    ports:
    - 9${BUILD}:9000
    volumes:
      - ~/sq/${SQ_VERSION}-${DB}/sqExtensions:/opt/sonarqube/extensions/plugins
      - ~/sq/${SQ_VERSION}-${DB}/sqConf:/opt/sonarqube/conf
      - ~/sq/${SQ_VERSION}-${DB}/sqLogs:/opt/sonarqube/logs
      - ~/sq/${SQ_VERSION}-${DB}/sqData:/opt/sonarqube/data
  db:
    container_name: pgsql-${SQ_VERSION}
    image: postgres:10
    ports:
      - 5${BUILD}:5432
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonardb
    volumes:
      - ~/sq/${SQ_VERSION}-${DB}/postgres:/var/lib/postgresql/data
    profiles:
      - dbs
volumes:
  sqExtensions:
    name: sqExtensions
  sqData:
    name: sqData
