version: '3.7'

services:
  sqb:
    container_name: sqb
    image: "sonarqube:${SQ_VERSION}"
    ports:
    - 9000:9000
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonardb
    volumes:
      - ~/sq/${SQ_VERSION}/sqExtensions:/opt/sonarqube/extensions
      - ~/sq/${SQ_VERSION}/sqConf:/opt/sonarqube/conf
      - ~/sq/${SQ_VERSION}/sqLogs:/opt/sonarqube/logs
      - ~/sq/${SQ_VERSION}/sqData:/opt/sonarqube/data
  db:
    container_name: "pgsql-${SQ_VERSION}"
    image: postgres:10
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonardb
    volumes:
      - ~/sq/${SQ_VERSION}/postgres:/var/lib/postgresql/data
volumes:
  sqExtensions:
    name: sqExtensions
  sqData:
    name: sqData